### ISSUE TITLE
Using curl before installing it?

### ISSUE THREAD

**Issue by BierLiebHaber** [Alexsogge/vs-resinvessel#11]
https://github.com/Alexsogge/vs-resinvessel/blob/0164c2b7f4d28b0d2a6e028cdd486936e1b5934f/Dockerfile#L9
https://github.com/Alexsogge/vs-resinvessel/blob/0164c2b7f4d28b0d2a6e028cdd486936e1b5934f/Dockerfile#L11
maybe you want to switch these lines.

**Comment by trigrab** [comment]
Good catch. In fact the installation is not necessary at all. `curl` is already installed in the mono base image. 

I made a PR here: #12 

As it is just a refactoring. I will merge it with the next change in the actual codebase.
